ubbagent's container is set to uid 0, add runAsUser 1001
This change is required due to the following error:

  Error: container has runAsNonRoot and image will run as root
  (pod: "cert-manager-apptest-1234, container: ubbagent)

Signed-off-by: Maël Valais <mael@vls.dev>