app-crd: the Application CRD breaks under CRD v1
For some reason, the Application that we have had a field that does not
exist on the v1beta1 spec. More specifically, we had:

  apiVersion: app.k8s.io/v1beta1
  kind: Application
  spec:
    descriptor:
      ...
      info: []

It should have been:

  apiVersion: app.k8s.io/v1beta1
  kind: Application
  spec:
    descriptor:
      ...
    info: []

It seems like when Google upgraded [1] the Application CRD from v1beta1
to v1 (this in the version of the CRD object, not the version of the
Application itself). After this change, the above Application manifest
could not be applied anymore. The error looked like this:

  error: error validating "/data/resources.yaml": error validating data:
  ValidationError(Application.spec.descriptor): unknown field "info" in
  io.k8s.app.v1beta1.Application.spec.descriptor; if you choose to ignore
  these errors, turn validation off with --validate=false

My guess is that before this change, the faulty "info" field was not
being validated, and the new v1 CRD version started validating it.

[1]: https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/pull/562

Signed-off-by: Maël Valais <mael@vls.dev>